# use x86_64, default is ia32
platform:
  - x64

# Test against the latest version of this Node.js version
environment:
  matrix:
    # node.js
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "12"
    - nodejs_version: "14"
    - nodejs_version: "16"
    - nodejs_version: "18"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run ci
  - npm run test

# Don't actually build.
build: off